/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FundTrace {
  export type CampaignStruct = {
    id: BigNumberish;
    creator: AddressLike;
    verifier: AddressLike;
    goal: BigNumberish;
    deadline: BigNumberish;
    totalDonated: BigNumberish;
    totalReleased: BigNumberish;
    metadataHash: BytesLike;
    state: BigNumberish;
    requestCount: BigNumberish;
    activeRequestId: BigNumberish;
    beneficiary: AddressLike;
    lastActivityTimestamp: BigNumberish;
    dormancySnapshotEscrow: BigNumberish;
    totalSanctioned: BigNumberish;
    totalAllocated: BigNumberish;
    totalClaimed: BigNumberish;
    quotationCount: BigNumberish;
  };

  export type CampaignStructOutput = [
    id: bigint,
    creator: string,
    verifier: string,
    goal: bigint,
    deadline: bigint,
    totalDonated: bigint,
    totalReleased: bigint,
    metadataHash: string,
    state: bigint,
    requestCount: bigint,
    activeRequestId: bigint,
    beneficiary: string,
    lastActivityTimestamp: bigint,
    dormancySnapshotEscrow: bigint,
    totalSanctioned: bigint,
    totalAllocated: bigint,
    totalClaimed: bigint,
    quotationCount: bigint
  ] & {
    id: bigint;
    creator: string;
    verifier: string;
    goal: bigint;
    deadline: bigint;
    totalDonated: bigint;
    totalReleased: bigint;
    metadataHash: string;
    state: bigint;
    requestCount: bigint;
    activeRequestId: bigint;
    beneficiary: string;
    lastActivityTimestamp: bigint;
    dormancySnapshotEscrow: bigint;
    totalSanctioned: bigint;
    totalAllocated: bigint;
    totalClaimed: bigint;
    quotationCount: bigint;
  };

  export type CreatorProfileStruct = {
    score: BigNumberish;
    totalQuotations: BigNumberish;
    approvedQuotations: BigNumberish;
    claimedAmount: BigNumberish;
    proofSubmitted: BigNumberish;
    onTimeProofs: BigNumberish;
    lateProofs: BigNumberish;
    missingProofs: BigNumberish;
    unresolvedRequests: BigNumberish;
    completedCampaigns: BigNumberish;
    lastUpdated: BigNumberish;
  };

  export type CreatorProfileStructOutput = [
    score: bigint,
    totalQuotations: bigint,
    approvedQuotations: bigint,
    claimedAmount: bigint,
    proofSubmitted: bigint,
    onTimeProofs: bigint,
    lateProofs: bigint,
    missingProofs: bigint,
    unresolvedRequests: bigint,
    completedCampaigns: bigint,
    lastUpdated: bigint
  ] & {
    score: bigint;
    totalQuotations: bigint;
    approvedQuotations: bigint;
    claimedAmount: bigint;
    proofSubmitted: bigint;
    onTimeProofs: bigint;
    lateProofs: bigint;
    missingProofs: bigint;
    unresolvedRequests: bigint;
    completedCampaigns: bigint;
    lastUpdated: bigint;
  };

  export type QuotationStruct = {
    id: BigNumberish;
    campaignId: BigNumberish;
    creator: AddressLike;
    requestedAmount: BigNumberish;
    quotationHash: BytesLike;
    submittedAt: BigNumberish;
    state: BigNumberish;
    allocatedAmount: BigNumberish;
    claimedAmount: BigNumberish;
    aiRecommendationHash: BytesLike;
    sanctionedAt: BigNumberish;
    claimedAt: BigNumberish;
    sanctionedBy: AddressLike;
    proofHash: BytesLike;
    proofSubmitted: boolean;
    proofSubmittedAt: BigNumberish;
    proofTiming: BigNumberish;
  };

  export type QuotationStructOutput = [
    id: bigint,
    campaignId: bigint,
    creator: string,
    requestedAmount: bigint,
    quotationHash: string,
    submittedAt: bigint,
    state: bigint,
    allocatedAmount: bigint,
    claimedAmount: bigint,
    aiRecommendationHash: string,
    sanctionedAt: bigint,
    claimedAt: bigint,
    sanctionedBy: string,
    proofHash: string,
    proofSubmitted: boolean,
    proofSubmittedAt: bigint,
    proofTiming: bigint
  ] & {
    id: bigint;
    campaignId: bigint;
    creator: string;
    requestedAmount: bigint;
    quotationHash: string;
    submittedAt: bigint;
    state: bigint;
    allocatedAmount: bigint;
    claimedAmount: bigint;
    aiRecommendationHash: string;
    sanctionedAt: bigint;
    claimedAt: bigint;
    sanctionedBy: string;
    proofHash: string;
    proofSubmitted: boolean;
    proofSubmittedAt: bigint;
    proofTiming: bigint;
  };

  export type RequestStruct = {
    id: BigNumberish;
    recipient: AddressLike;
    amount: BigNumberish;
    requestHash: BytesLike;
    votingDeadline: BigNumberish;
    proofDeadline: BigNumberish;
    approvalWeight: BigNumberish;
    state: BigNumberish;
    receiptHash: BytesLike;
    proofSubmitted: boolean;
    releasedAt: BigNumberish;
    proofSubmittedAt: BigNumberish;
    timing: BigNumberish;
    deliveryConfirmed: boolean;
    deliveryConfirmedAt: BigNumberish;
  };

  export type RequestStructOutput = [
    id: bigint,
    recipient: string,
    amount: bigint,
    requestHash: string,
    votingDeadline: bigint,
    proofDeadline: bigint,
    approvalWeight: bigint,
    state: bigint,
    receiptHash: string,
    proofSubmitted: boolean,
    releasedAt: bigint,
    proofSubmittedAt: bigint,
    timing: bigint,
    deliveryConfirmed: boolean,
    deliveryConfirmedAt: bigint
  ] & {
    id: bigint;
    recipient: string;
    amount: bigint;
    requestHash: string;
    votingDeadline: bigint;
    proofDeadline: bigint;
    approvalWeight: bigint;
    state: bigint;
    receiptHash: string;
    proofSubmitted: boolean;
    releasedAt: bigint;
    proofSubmittedAt: bigint;
    timing: bigint;
    deliveryConfirmed: boolean;
    deliveryConfirmedAt: bigint;
  };
}

export interface FundTraceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DORMANCY_TIMEOUT"
      | "MAX_SCORE"
      | "admin"
      | "approveRequest"
      | "campaignCount"
      | "campaigns"
      | "checkAndUpdateCampaignFailure"
      | "checkProofHash"
      | "claimAllocation"
      | "claimDormancyRefund"
      | "closeExpiredRequest"
      | "completeQuotation"
      | "confirmDelivery"
      | "createCampaign"
      | "createRequest"
      | "creatorProfiles"
      | "disableAutomation"
      | "donate"
      | "donations"
      | "donorAutomation"
      | "enableAutomation"
      | "getCampaign"
      | "getCampaignFinancials"
      | "getCreatorProfile"
      | "getQuotation"
      | "getRequest"
      | "hasOverdueProof"
      | "hasUnconfirmedDelivery"
      | "hasVoted"
      | "isCampaignDormant"
      | "isDonorAutomationEnabled"
      | "quotations"
      | "recordAIRecommendation"
      | "refund"
      | "registerQuotation"
      | "rejectCampaign"
      | "rejectQuotation"
      | "release"
      | "requests"
      | "sanctionQuotation"
      | "setBeneficiary"
      | "submitProof"
      | "submitQuotationProof"
      | "trustedRelayAddress"
      | "updateCreatorScore"
      | "verifyCampaign"
      | "vote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AllocationClaimed"
      | "Approved"
      | "AutomationToggled"
      | "BeneficiarySet"
      | "CampaignCreated"
      | "CampaignFailed"
      | "CampaignRejected"
      | "CampaignVerified"
      | "CreatorScoreUpdated"
      | "DeliveryConfirmed"
      | "Donated"
      | "DormancyRefundClaimed"
      | "FundingClosed"
      | "ProofSubmitted"
      | "QuotationAIEvaluated"
      | "QuotationProofSubmitted"
      | "QuotationRegistered"
      | "QuotationRejected"
      | "QuotationSanctioned"
      | "Refunded"
      | "Released"
      | "RequestApproved"
      | "RequestClosed"
      | "RequestCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DORMANCY_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_SCORE", values?: undefined): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approveRequest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAndUpdateCampaignFailure",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkProofHash",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAllocation",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDormancyRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeExpiredRequest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeQuotation",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmDelivery",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [BigNumberish, BigNumberish, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createRequest",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorProfiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disableAutomation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "donate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "donations",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "donorAutomation",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "enableAutomation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignFinancials",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuotation",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasOverdueProof",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUnconfirmedDelivery",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCampaignDormant",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isDonorAutomationEnabled",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "quotations",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordAIRecommendation",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerQuotation",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectCampaign",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectQuotation",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "release",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requests",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sanctionQuotation",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBeneficiary",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitQuotationProof",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedRelayAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateCreatorScore",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DORMANCY_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_SCORE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkAndUpdateCampaignFailure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkProofHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimDormancyRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeExpiredRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeQuotation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorProfiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableAutomation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "donations", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "donorAutomation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableAutomation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignFinancials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuotation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRequest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasOverdueProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUnconfirmedDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCampaignDormant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDonorAutomationEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quotations", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordAIRecommendation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerQuotation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectQuotation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sanctionQuotation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitQuotationProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedRelayAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCreatorScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace AllocationClaimedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    quotationId: BigNumberish,
    creator: AddressLike,
    claimedAmount: BigNumberish,
    remainingAllocation: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    quotationId: bigint,
    creator: string,
    claimedAmount: bigint,
    remainingAllocation: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    quotationId: bigint;
    creator: string;
    claimedAmount: bigint;
    remainingAllocation: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    requestId: BigNumberish,
    donor: AddressLike,
    weight: BigNumberish,
    currentApprovalWeight: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    requestId: bigint,
    donor: string,
    weight: bigint,
    currentApprovalWeight: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    requestId: bigint;
    donor: string;
    weight: bigint;
    currentApprovalWeight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AutomationToggledEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    donor: AddressLike,
    enabled: boolean
  ];
  export type OutputTuple = [
    campaignId: bigint,
    donor: string,
    enabled: boolean
  ];
  export interface OutputObject {
    campaignId: bigint;
    donor: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeneficiarySetEvent {
  export type InputTuple = [campaignId: BigNumberish, beneficiary: AddressLike];
  export type OutputTuple = [campaignId: bigint, beneficiary: string];
  export interface OutputObject {
    campaignId: bigint;
    beneficiary: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    creator: AddressLike,
    verifier: AddressLike,
    goal: BigNumberish,
    deadline: BigNumberish,
    metadataHash: BytesLike
  ];
  export type OutputTuple = [
    campaignId: bigint,
    creator: string,
    verifier: string,
    goal: bigint,
    deadline: bigint,
    metadataHash: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    creator: string;
    verifier: string;
    goal: bigint;
    deadline: bigint;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignFailedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    totalDonated: BigNumberish,
    goal: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    totalDonated: bigint,
    goal: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    totalDonated: bigint;
    goal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignRejectedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    verifier: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    campaignId: bigint,
    verifier: string,
    reason: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    verifier: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignVerifiedEvent {
  export type InputTuple = [campaignId: BigNumberish, verifier: AddressLike];
  export type OutputTuple = [campaignId: bigint, verifier: string];
  export interface OutputObject {
    campaignId: bigint;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreatorScoreUpdatedEvent {
  export type InputTuple = [
    creator: AddressLike,
    oldScore: BigNumberish,
    newScore: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    creator: string,
    oldScore: bigint,
    newScore: bigint,
    reason: string
  ];
  export interface OutputObject {
    creator: string;
    oldScore: bigint;
    newScore: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeliveryConfirmedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    requestId: BigNumberish,
    beneficiary: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    requestId: bigint,
    beneficiary: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    requestId: bigint;
    beneficiary: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DonatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    donor: AddressLike,
    amount: BigNumberish,
    totalDonated: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    donor: string,
    amount: bigint,
    totalDonated: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    donor: string;
    amount: bigint;
    totalDonated: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DormancyRefundClaimedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    donor: AddressLike,
    amount: BigNumberish,
    remainingEscrow: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    donor: string,
    amount: bigint,
    remainingEscrow: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    donor: string;
    amount: bigint;
    remainingEscrow: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundingClosedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    totalRaised: BigNumberish
  ];
  export type OutputTuple = [campaignId: bigint, totalRaised: bigint];
  export interface OutputObject {
    campaignId: bigint;
    totalRaised: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofSubmittedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    requestId: BigNumberish,
    receiptHash: BytesLike,
    isLate: boolean,
    submittedAt: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    requestId: bigint,
    receiptHash: string,
    isLate: boolean,
    submittedAt: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    requestId: bigint;
    receiptHash: string;
    isLate: boolean;
    submittedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuotationAIEvaluatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    quotationId: BigNumberish,
    aiRecommendationHash: BytesLike
  ];
  export type OutputTuple = [
    campaignId: bigint,
    quotationId: bigint,
    aiRecommendationHash: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    quotationId: bigint;
    aiRecommendationHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuotationProofSubmittedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    quotationId: BigNumberish,
    proofHash: BytesLike,
    isLate: boolean,
    submittedAt: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    quotationId: bigint,
    proofHash: string,
    isLate: boolean,
    submittedAt: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    quotationId: bigint;
    proofHash: string;
    isLate: boolean;
    submittedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuotationRegisteredEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    quotationId: BigNumberish,
    creator: AddressLike,
    requestedAmount: BigNumberish,
    quotationHash: BytesLike,
    submittedAt: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    quotationId: bigint,
    creator: string,
    requestedAmount: bigint,
    quotationHash: string,
    submittedAt: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    quotationId: bigint;
    creator: string;
    requestedAmount: bigint;
    quotationHash: string;
    submittedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuotationRejectedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    quotationId: BigNumberish,
    rejectedBy: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    campaignId: bigint,
    quotationId: bigint,
    rejectedBy: string,
    reason: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    quotationId: bigint;
    rejectedBy: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuotationSanctionedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    quotationId: BigNumberish,
    sanctionedBy: AddressLike,
    allocatedAmount: BigNumberish,
    isAutomated: boolean
  ];
  export type OutputTuple = [
    campaignId: bigint,
    quotationId: bigint,
    sanctionedBy: string,
    allocatedAmount: bigint,
    isAutomated: boolean
  ];
  export interface OutputObject {
    campaignId: bigint;
    quotationId: bigint;
    sanctionedBy: string;
    allocatedAmount: bigint;
    isAutomated: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    donor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [campaignId: bigint, donor: string, amount: bigint];
  export interface OutputObject {
    campaignId: bigint;
    donor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleasedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    requestId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    requestId: bigint,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    requestId: bigint;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestApprovedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    requestId: BigNumberish,
    totalApprovalWeight: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    requestId: bigint,
    totalApprovalWeight: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    requestId: bigint;
    totalApprovalWeight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestClosedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    requestId: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    campaignId: bigint,
    requestId: bigint,
    reason: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    requestId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestCreatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    requestId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish,
    requestHash: BytesLike,
    votingDeadline: BigNumberish,
    proofDeadline: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    requestId: bigint,
    recipient: string,
    amount: bigint,
    requestHash: string,
    votingDeadline: bigint,
    proofDeadline: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    requestId: bigint;
    recipient: string;
    amount: bigint;
    requestHash: string;
    votingDeadline: bigint;
    proofDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FundTrace extends BaseContract {
  connect(runner?: ContractRunner | null): FundTrace;
  waitForDeployment(): Promise<this>;

  interface: FundTraceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DORMANCY_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  MAX_SCORE: TypedContractMethod<[], [bigint], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  approveRequest: TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  campaignCount: TypedContractMethod<[], [bigint], "view">;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        creator: string;
        verifier: string;
        goal: bigint;
        deadline: bigint;
        totalDonated: bigint;
        totalReleased: bigint;
        metadataHash: string;
        state: bigint;
        requestCount: bigint;
        activeRequestId: bigint;
        beneficiary: string;
        lastActivityTimestamp: bigint;
        dormancySnapshotEscrow: bigint;
        totalSanctioned: bigint;
        totalAllocated: bigint;
        totalClaimed: bigint;
        quotationCount: bigint;
      }
    ],
    "view"
  >;

  checkAndUpdateCampaignFailure: TypedContractMethod<
    [_campaignId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  checkProofHash: TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _requestId: BigNumberish,
      _candidateHash: BytesLike
    ],
    [
      [boolean, boolean, bigint] & {
        matches: boolean;
        isSubmitted: boolean;
        timing: bigint;
      }
    ],
    "view"
  >;

  claimAllocation: TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _quotationId: BigNumberish,
      _claimAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  claimDormancyRefund: TypedContractMethod<
    [_campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  closeExpiredRequest: TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  completeQuotation: TypedContractMethod<
    [_campaignId: BigNumberish, _quotationId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confirmDelivery: TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createCampaign: TypedContractMethod<
    [
      _goal: BigNumberish,
      _deadline: BigNumberish,
      _metadataHash: BytesLike,
      _verifier: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  createRequest: TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _recipient: AddressLike,
      _amount: BigNumberish,
      _requestHash: BytesLike,
      _votingDuration: BigNumberish,
      _proofDuration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  creatorProfiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        score: bigint;
        totalQuotations: bigint;
        approvedQuotations: bigint;
        claimedAmount: bigint;
        proofSubmitted: bigint;
        onTimeProofs: bigint;
        lateProofs: bigint;
        missingProofs: bigint;
        unresolvedRequests: bigint;
        completedCampaigns: bigint;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;

  disableAutomation: TypedContractMethod<
    [_campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  donate: TypedContractMethod<[_campaignId: BigNumberish], [void], "payable">;

  donations: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  donorAutomation: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  enableAutomation: TypedContractMethod<
    [_campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCampaign: TypedContractMethod<
    [_campaignId: BigNumberish],
    [FundTrace.CampaignStructOutput],
    "view"
  >;

  getCampaignFinancials: TypedContractMethod<
    [_campaignId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalRaised: bigint;
        totalAllocated: bigint;
        totalSanctioned: bigint;
        totalClaimed: bigint;
        proofBackedAmount: bigint;
        remainingAllocation: bigint;
      }
    ],
    "view"
  >;

  getCreatorProfile: TypedContractMethod<
    [_creator: AddressLike],
    [FundTrace.CreatorProfileStructOutput],
    "view"
  >;

  getQuotation: TypedContractMethod<
    [_campaignId: BigNumberish, _quotationId: BigNumberish],
    [FundTrace.QuotationStructOutput],
    "view"
  >;

  getRequest: TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [FundTrace.RequestStructOutput],
    "view"
  >;

  hasOverdueProof: TypedContractMethod<
    [_campaignId: BigNumberish],
    [boolean],
    "view"
  >;

  hasUnconfirmedDelivery: TypedContractMethod<
    [_campaignId: BigNumberish],
    [boolean],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [boolean],
    "view"
  >;

  isCampaignDormant: TypedContractMethod<
    [_campaignId: BigNumberish],
    [boolean],
    "view"
  >;

  isDonorAutomationEnabled: TypedContractMethod<
    [_campaignId: BigNumberish, _donor: AddressLike],
    [boolean],
    "view"
  >;

  quotations: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
        string,
        boolean,
        bigint,
        bigint
      ] & {
        id: bigint;
        campaignId: bigint;
        creator: string;
        requestedAmount: bigint;
        quotationHash: string;
        submittedAt: bigint;
        state: bigint;
        allocatedAmount: bigint;
        claimedAmount: bigint;
        aiRecommendationHash: string;
        sanctionedAt: bigint;
        claimedAt: bigint;
        sanctionedBy: string;
        proofHash: string;
        proofSubmitted: boolean;
        proofSubmittedAt: bigint;
        proofTiming: bigint;
      }
    ],
    "view"
  >;

  recordAIRecommendation: TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _quotationId: BigNumberish,
      _aiRecommendationHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  refund: TypedContractMethod<
    [_campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerQuotation: TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _requestedAmount: BigNumberish,
      _quotationHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  rejectCampaign: TypedContractMethod<
    [_campaignId: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;

  rejectQuotation: TypedContractMethod<
    [_campaignId: BigNumberish, _quotationId: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;

  release: TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  requests: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        recipient: string;
        amount: bigint;
        requestHash: string;
        votingDeadline: bigint;
        proofDeadline: bigint;
        approvalWeight: bigint;
        state: bigint;
        receiptHash: string;
        proofSubmitted: boolean;
        releasedAt: bigint;
        proofSubmittedAt: bigint;
        timing: bigint;
        deliveryConfirmed: boolean;
        deliveryConfirmedAt: bigint;
      }
    ],
    "view"
  >;

  sanctionQuotation: TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _quotationId: BigNumberish,
      _allocatedAmount: BigNumberish,
      _isAutomated: boolean,
      _onBehalfOfDonor: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  setBeneficiary: TypedContractMethod<
    [_campaignId: BigNumberish, _beneficiary: AddressLike],
    [void],
    "nonpayable"
  >;

  submitProof: TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _requestId: BigNumberish,
      _receiptHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  submitQuotationProof: TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _quotationId: BigNumberish,
      _proofHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  trustedRelayAddress: TypedContractMethod<[], [string], "view">;

  updateCreatorScore: TypedContractMethod<
    [_creator: AddressLike, _newScore: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;

  verifyCampaign: TypedContractMethod<
    [_campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DORMANCY_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveRequest"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "campaignCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        creator: string;
        verifier: string;
        goal: bigint;
        deadline: bigint;
        totalDonated: bigint;
        totalReleased: bigint;
        metadataHash: string;
        state: bigint;
        requestCount: bigint;
        activeRequestId: bigint;
        beneficiary: string;
        lastActivityTimestamp: bigint;
        dormancySnapshotEscrow: bigint;
        totalSanctioned: bigint;
        totalAllocated: bigint;
        totalClaimed: bigint;
        quotationCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkAndUpdateCampaignFailure"
  ): TypedContractMethod<[_campaignId: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "checkProofHash"
  ): TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _requestId: BigNumberish,
      _candidateHash: BytesLike
    ],
    [
      [boolean, boolean, bigint] & {
        matches: boolean;
        isSubmitted: boolean;
        timing: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimAllocation"
  ): TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _quotationId: BigNumberish,
      _claimAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimDormancyRefund"
  ): TypedContractMethod<[_campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "closeExpiredRequest"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "completeQuotation"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _quotationId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confirmDelivery"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      _goal: BigNumberish,
      _deadline: BigNumberish,
      _metadataHash: BytesLike,
      _verifier: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createRequest"
  ): TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _recipient: AddressLike,
      _amount: BigNumberish,
      _requestHash: BytesLike,
      _votingDuration: BigNumberish,
      _proofDuration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creatorProfiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        score: bigint;
        totalQuotations: bigint;
        approvedQuotations: bigint;
        claimedAmount: bigint;
        proofSubmitted: bigint;
        onTimeProofs: bigint;
        lateProofs: bigint;
        missingProofs: bigint;
        unresolvedRequests: bigint;
        completedCampaigns: bigint;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "disableAutomation"
  ): TypedContractMethod<[_campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "donate"
  ): TypedContractMethod<[_campaignId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "donations"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "donorAutomation"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "enableAutomation"
  ): TypedContractMethod<[_campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCampaign"
  ): TypedContractMethod<
    [_campaignId: BigNumberish],
    [FundTrace.CampaignStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCampaignFinancials"
  ): TypedContractMethod<
    [_campaignId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalRaised: bigint;
        totalAllocated: bigint;
        totalSanctioned: bigint;
        totalClaimed: bigint;
        proofBackedAmount: bigint;
        remainingAllocation: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCreatorProfile"
  ): TypedContractMethod<
    [_creator: AddressLike],
    [FundTrace.CreatorProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getQuotation"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _quotationId: BigNumberish],
    [FundTrace.QuotationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRequest"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [FundTrace.RequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasOverdueProof"
  ): TypedContractMethod<[_campaignId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasUnconfirmedDelivery"
  ): TypedContractMethod<[_campaignId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCampaignDormant"
  ): TypedContractMethod<[_campaignId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isDonorAutomationEnabled"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _donor: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "quotations"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
        string,
        boolean,
        bigint,
        bigint
      ] & {
        id: bigint;
        campaignId: bigint;
        creator: string;
        requestedAmount: bigint;
        quotationHash: string;
        submittedAt: bigint;
        state: bigint;
        allocatedAmount: bigint;
        claimedAmount: bigint;
        aiRecommendationHash: string;
        sanctionedAt: bigint;
        claimedAt: bigint;
        sanctionedBy: string;
        proofHash: string;
        proofSubmitted: boolean;
        proofSubmittedAt: bigint;
        proofTiming: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordAIRecommendation"
  ): TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _quotationId: BigNumberish,
      _aiRecommendationHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[_campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerQuotation"
  ): TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _requestedAmount: BigNumberish,
      _quotationHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectCampaign"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectQuotation"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _quotationId: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        recipient: string;
        amount: bigint;
        requestHash: string;
        votingDeadline: bigint;
        proofDeadline: bigint;
        approvalWeight: bigint;
        state: bigint;
        receiptHash: string;
        proofSubmitted: boolean;
        releasedAt: bigint;
        proofSubmittedAt: bigint;
        timing: bigint;
        deliveryConfirmed: boolean;
        deliveryConfirmedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "sanctionQuotation"
  ): TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _quotationId: BigNumberish,
      _allocatedAmount: BigNumberish,
      _isAutomated: boolean,
      _onBehalfOfDonor: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBeneficiary"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _beneficiary: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _requestId: BigNumberish,
      _receiptHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitQuotationProof"
  ): TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _quotationId: BigNumberish,
      _proofHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "trustedRelayAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateCreatorScore"
  ): TypedContractMethod<
    [_creator: AddressLike, _newScore: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyCampaign"
  ): TypedContractMethod<[_campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AllocationClaimed"
  ): TypedContractEvent<
    AllocationClaimedEvent.InputTuple,
    AllocationClaimedEvent.OutputTuple,
    AllocationClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Approved"
  ): TypedContractEvent<
    ApprovedEvent.InputTuple,
    ApprovedEvent.OutputTuple,
    ApprovedEvent.OutputObject
  >;
  getEvent(
    key: "AutomationToggled"
  ): TypedContractEvent<
    AutomationToggledEvent.InputTuple,
    AutomationToggledEvent.OutputTuple,
    AutomationToggledEvent.OutputObject
  >;
  getEvent(
    key: "BeneficiarySet"
  ): TypedContractEvent<
    BeneficiarySetEvent.InputTuple,
    BeneficiarySetEvent.OutputTuple,
    BeneficiarySetEvent.OutputObject
  >;
  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignFailed"
  ): TypedContractEvent<
    CampaignFailedEvent.InputTuple,
    CampaignFailedEvent.OutputTuple,
    CampaignFailedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignRejected"
  ): TypedContractEvent<
    CampaignRejectedEvent.InputTuple,
    CampaignRejectedEvent.OutputTuple,
    CampaignRejectedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignVerified"
  ): TypedContractEvent<
    CampaignVerifiedEvent.InputTuple,
    CampaignVerifiedEvent.OutputTuple,
    CampaignVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "CreatorScoreUpdated"
  ): TypedContractEvent<
    CreatorScoreUpdatedEvent.InputTuple,
    CreatorScoreUpdatedEvent.OutputTuple,
    CreatorScoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DeliveryConfirmed"
  ): TypedContractEvent<
    DeliveryConfirmedEvent.InputTuple,
    DeliveryConfirmedEvent.OutputTuple,
    DeliveryConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "Donated"
  ): TypedContractEvent<
    DonatedEvent.InputTuple,
    DonatedEvent.OutputTuple,
    DonatedEvent.OutputObject
  >;
  getEvent(
    key: "DormancyRefundClaimed"
  ): TypedContractEvent<
    DormancyRefundClaimedEvent.InputTuple,
    DormancyRefundClaimedEvent.OutputTuple,
    DormancyRefundClaimedEvent.OutputObject
  >;
  getEvent(
    key: "FundingClosed"
  ): TypedContractEvent<
    FundingClosedEvent.InputTuple,
    FundingClosedEvent.OutputTuple,
    FundingClosedEvent.OutputObject
  >;
  getEvent(
    key: "ProofSubmitted"
  ): TypedContractEvent<
    ProofSubmittedEvent.InputTuple,
    ProofSubmittedEvent.OutputTuple,
    ProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "QuotationAIEvaluated"
  ): TypedContractEvent<
    QuotationAIEvaluatedEvent.InputTuple,
    QuotationAIEvaluatedEvent.OutputTuple,
    QuotationAIEvaluatedEvent.OutputObject
  >;
  getEvent(
    key: "QuotationProofSubmitted"
  ): TypedContractEvent<
    QuotationProofSubmittedEvent.InputTuple,
    QuotationProofSubmittedEvent.OutputTuple,
    QuotationProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "QuotationRegistered"
  ): TypedContractEvent<
    QuotationRegisteredEvent.InputTuple,
    QuotationRegisteredEvent.OutputTuple,
    QuotationRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "QuotationRejected"
  ): TypedContractEvent<
    QuotationRejectedEvent.InputTuple,
    QuotationRejectedEvent.OutputTuple,
    QuotationRejectedEvent.OutputObject
  >;
  getEvent(
    key: "QuotationSanctioned"
  ): TypedContractEvent<
    QuotationSanctionedEvent.InputTuple,
    QuotationSanctionedEvent.OutputTuple,
    QuotationSanctionedEvent.OutputObject
  >;
  getEvent(
    key: "Refunded"
  ): TypedContractEvent<
    RefundedEvent.InputTuple,
    RefundedEvent.OutputTuple,
    RefundedEvent.OutputObject
  >;
  getEvent(
    key: "Released"
  ): TypedContractEvent<
    ReleasedEvent.InputTuple,
    ReleasedEvent.OutputTuple,
    ReleasedEvent.OutputObject
  >;
  getEvent(
    key: "RequestApproved"
  ): TypedContractEvent<
    RequestApprovedEvent.InputTuple,
    RequestApprovedEvent.OutputTuple,
    RequestApprovedEvent.OutputObject
  >;
  getEvent(
    key: "RequestClosed"
  ): TypedContractEvent<
    RequestClosedEvent.InputTuple,
    RequestClosedEvent.OutputTuple,
    RequestClosedEvent.OutputObject
  >;
  getEvent(
    key: "RequestCreated"
  ): TypedContractEvent<
    RequestCreatedEvent.InputTuple,
    RequestCreatedEvent.OutputTuple,
    RequestCreatedEvent.OutputObject
  >;

  filters: {
    "AllocationClaimed(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      AllocationClaimedEvent.InputTuple,
      AllocationClaimedEvent.OutputTuple,
      AllocationClaimedEvent.OutputObject
    >;
    AllocationClaimed: TypedContractEvent<
      AllocationClaimedEvent.InputTuple,
      AllocationClaimedEvent.OutputTuple,
      AllocationClaimedEvent.OutputObject
    >;

    "Approved(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      ApprovedEvent.InputTuple,
      ApprovedEvent.OutputTuple,
      ApprovedEvent.OutputObject
    >;
    Approved: TypedContractEvent<
      ApprovedEvent.InputTuple,
      ApprovedEvent.OutputTuple,
      ApprovedEvent.OutputObject
    >;

    "AutomationToggled(uint256,address,bool)": TypedContractEvent<
      AutomationToggledEvent.InputTuple,
      AutomationToggledEvent.OutputTuple,
      AutomationToggledEvent.OutputObject
    >;
    AutomationToggled: TypedContractEvent<
      AutomationToggledEvent.InputTuple,
      AutomationToggledEvent.OutputTuple,
      AutomationToggledEvent.OutputObject
    >;

    "BeneficiarySet(uint256,address)": TypedContractEvent<
      BeneficiarySetEvent.InputTuple,
      BeneficiarySetEvent.OutputTuple,
      BeneficiarySetEvent.OutputObject
    >;
    BeneficiarySet: TypedContractEvent<
      BeneficiarySetEvent.InputTuple,
      BeneficiarySetEvent.OutputTuple,
      BeneficiarySetEvent.OutputObject
    >;

    "CampaignCreated(uint256,address,address,uint256,uint256,bytes32)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "CampaignFailed(uint256,uint256,uint256)": TypedContractEvent<
      CampaignFailedEvent.InputTuple,
      CampaignFailedEvent.OutputTuple,
      CampaignFailedEvent.OutputObject
    >;
    CampaignFailed: TypedContractEvent<
      CampaignFailedEvent.InputTuple,
      CampaignFailedEvent.OutputTuple,
      CampaignFailedEvent.OutputObject
    >;

    "CampaignRejected(uint256,address,string)": TypedContractEvent<
      CampaignRejectedEvent.InputTuple,
      CampaignRejectedEvent.OutputTuple,
      CampaignRejectedEvent.OutputObject
    >;
    CampaignRejected: TypedContractEvent<
      CampaignRejectedEvent.InputTuple,
      CampaignRejectedEvent.OutputTuple,
      CampaignRejectedEvent.OutputObject
    >;

    "CampaignVerified(uint256,address)": TypedContractEvent<
      CampaignVerifiedEvent.InputTuple,
      CampaignVerifiedEvent.OutputTuple,
      CampaignVerifiedEvent.OutputObject
    >;
    CampaignVerified: TypedContractEvent<
      CampaignVerifiedEvent.InputTuple,
      CampaignVerifiedEvent.OutputTuple,
      CampaignVerifiedEvent.OutputObject
    >;

    "CreatorScoreUpdated(address,uint256,uint256,string)": TypedContractEvent<
      CreatorScoreUpdatedEvent.InputTuple,
      CreatorScoreUpdatedEvent.OutputTuple,
      CreatorScoreUpdatedEvent.OutputObject
    >;
    CreatorScoreUpdated: TypedContractEvent<
      CreatorScoreUpdatedEvent.InputTuple,
      CreatorScoreUpdatedEvent.OutputTuple,
      CreatorScoreUpdatedEvent.OutputObject
    >;

    "DeliveryConfirmed(uint256,uint256,address,uint256)": TypedContractEvent<
      DeliveryConfirmedEvent.InputTuple,
      DeliveryConfirmedEvent.OutputTuple,
      DeliveryConfirmedEvent.OutputObject
    >;
    DeliveryConfirmed: TypedContractEvent<
      DeliveryConfirmedEvent.InputTuple,
      DeliveryConfirmedEvent.OutputTuple,
      DeliveryConfirmedEvent.OutputObject
    >;

    "Donated(uint256,address,uint256,uint256)": TypedContractEvent<
      DonatedEvent.InputTuple,
      DonatedEvent.OutputTuple,
      DonatedEvent.OutputObject
    >;
    Donated: TypedContractEvent<
      DonatedEvent.InputTuple,
      DonatedEvent.OutputTuple,
      DonatedEvent.OutputObject
    >;

    "DormancyRefundClaimed(uint256,address,uint256,uint256)": TypedContractEvent<
      DormancyRefundClaimedEvent.InputTuple,
      DormancyRefundClaimedEvent.OutputTuple,
      DormancyRefundClaimedEvent.OutputObject
    >;
    DormancyRefundClaimed: TypedContractEvent<
      DormancyRefundClaimedEvent.InputTuple,
      DormancyRefundClaimedEvent.OutputTuple,
      DormancyRefundClaimedEvent.OutputObject
    >;

    "FundingClosed(uint256,uint256)": TypedContractEvent<
      FundingClosedEvent.InputTuple,
      FundingClosedEvent.OutputTuple,
      FundingClosedEvent.OutputObject
    >;
    FundingClosed: TypedContractEvent<
      FundingClosedEvent.InputTuple,
      FundingClosedEvent.OutputTuple,
      FundingClosedEvent.OutputObject
    >;

    "ProofSubmitted(uint256,uint256,bytes32,bool,uint256)": TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;
    ProofSubmitted: TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;

    "QuotationAIEvaluated(uint256,uint256,bytes32)": TypedContractEvent<
      QuotationAIEvaluatedEvent.InputTuple,
      QuotationAIEvaluatedEvent.OutputTuple,
      QuotationAIEvaluatedEvent.OutputObject
    >;
    QuotationAIEvaluated: TypedContractEvent<
      QuotationAIEvaluatedEvent.InputTuple,
      QuotationAIEvaluatedEvent.OutputTuple,
      QuotationAIEvaluatedEvent.OutputObject
    >;

    "QuotationProofSubmitted(uint256,uint256,bytes32,bool,uint256)": TypedContractEvent<
      QuotationProofSubmittedEvent.InputTuple,
      QuotationProofSubmittedEvent.OutputTuple,
      QuotationProofSubmittedEvent.OutputObject
    >;
    QuotationProofSubmitted: TypedContractEvent<
      QuotationProofSubmittedEvent.InputTuple,
      QuotationProofSubmittedEvent.OutputTuple,
      QuotationProofSubmittedEvent.OutputObject
    >;

    "QuotationRegistered(uint256,uint256,address,uint256,bytes32,uint256)": TypedContractEvent<
      QuotationRegisteredEvent.InputTuple,
      QuotationRegisteredEvent.OutputTuple,
      QuotationRegisteredEvent.OutputObject
    >;
    QuotationRegistered: TypedContractEvent<
      QuotationRegisteredEvent.InputTuple,
      QuotationRegisteredEvent.OutputTuple,
      QuotationRegisteredEvent.OutputObject
    >;

    "QuotationRejected(uint256,uint256,address,string)": TypedContractEvent<
      QuotationRejectedEvent.InputTuple,
      QuotationRejectedEvent.OutputTuple,
      QuotationRejectedEvent.OutputObject
    >;
    QuotationRejected: TypedContractEvent<
      QuotationRejectedEvent.InputTuple,
      QuotationRejectedEvent.OutputTuple,
      QuotationRejectedEvent.OutputObject
    >;

    "QuotationSanctioned(uint256,uint256,address,uint256,bool)": TypedContractEvent<
      QuotationSanctionedEvent.InputTuple,
      QuotationSanctionedEvent.OutputTuple,
      QuotationSanctionedEvent.OutputObject
    >;
    QuotationSanctioned: TypedContractEvent<
      QuotationSanctionedEvent.InputTuple,
      QuotationSanctionedEvent.OutputTuple,
      QuotationSanctionedEvent.OutputObject
    >;

    "Refunded(uint256,address,uint256)": TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
    Refunded: TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;

    "Released(uint256,uint256,address,uint256)": TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;
    Released: TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;

    "RequestApproved(uint256,uint256,uint256)": TypedContractEvent<
      RequestApprovedEvent.InputTuple,
      RequestApprovedEvent.OutputTuple,
      RequestApprovedEvent.OutputObject
    >;
    RequestApproved: TypedContractEvent<
      RequestApprovedEvent.InputTuple,
      RequestApprovedEvent.OutputTuple,
      RequestApprovedEvent.OutputObject
    >;

    "RequestClosed(uint256,uint256,string)": TypedContractEvent<
      RequestClosedEvent.InputTuple,
      RequestClosedEvent.OutputTuple,
      RequestClosedEvent.OutputObject
    >;
    RequestClosed: TypedContractEvent<
      RequestClosedEvent.InputTuple,
      RequestClosedEvent.OutputTuple,
      RequestClosedEvent.OutputObject
    >;

    "RequestCreated(uint256,uint256,address,uint256,bytes32,uint256,uint256)": TypedContractEvent<
      RequestCreatedEvent.InputTuple,
      RequestCreatedEvent.OutputTuple,
      RequestCreatedEvent.OutputObject
    >;
    RequestCreated: TypedContractEvent<
      RequestCreatedEvent.InputTuple,
      RequestCreatedEvent.OutputTuple,
      RequestCreatedEvent.OutputObject
    >;
  };
}
