/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FundTrace {
  export type CampaignStruct = {
    id: BigNumberish;
    creator: AddressLike;
    verifier: AddressLike;
    goal: BigNumberish;
    deadline: BigNumberish;
    totalDonated: BigNumberish;
    totalReleased: BigNumberish;
    metadataHash: BytesLike;
    state: BigNumberish;
    requestCount: BigNumberish;
    activeRequestId: BigNumberish;
  };

  export type CampaignStructOutput = [
    id: bigint,
    creator: string,
    verifier: string,
    goal: bigint,
    deadline: bigint,
    totalDonated: bigint,
    totalReleased: bigint,
    metadataHash: string,
    state: bigint,
    requestCount: bigint,
    activeRequestId: bigint
  ] & {
    id: bigint;
    creator: string;
    verifier: string;
    goal: bigint;
    deadline: bigint;
    totalDonated: bigint;
    totalReleased: bigint;
    metadataHash: string;
    state: bigint;
    requestCount: bigint;
    activeRequestId: bigint;
  };

  export type RequestStruct = {
    id: BigNumberish;
    recipient: AddressLike;
    amount: BigNumberish;
    requestHash: BytesLike;
    votingDeadline: BigNumberish;
    proofDeadline: BigNumberish;
    approvalWeight: BigNumberish;
    state: BigNumberish;
    receiptHash: BytesLike;
    proofSubmitted: boolean;
    releasedAt: BigNumberish;
    proofSubmittedAt: BigNumberish;
    timing: BigNumberish;
  };

  export type RequestStructOutput = [
    id: bigint,
    recipient: string,
    amount: bigint,
    requestHash: string,
    votingDeadline: bigint,
    proofDeadline: bigint,
    approvalWeight: bigint,
    state: bigint,
    receiptHash: string,
    proofSubmitted: boolean,
    releasedAt: bigint,
    proofSubmittedAt: bigint,
    timing: bigint
  ] & {
    id: bigint;
    recipient: string;
    amount: bigint;
    requestHash: string;
    votingDeadline: bigint;
    proofDeadline: bigint;
    approvalWeight: bigint;
    state: bigint;
    receiptHash: string;
    proofSubmitted: boolean;
    releasedAt: bigint;
    proofSubmittedAt: bigint;
    timing: bigint;
  };
}

export interface FundTraceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveRequest"
      | "campaignCount"
      | "campaigns"
      | "checkAndUpdateCampaignFailure"
      | "checkProofHash"
      | "closeExpiredRequest"
      | "createCampaign"
      | "createRequest"
      | "donate"
      | "donations"
      | "getCampaign"
      | "getRequest"
      | "hasOverdueProof"
      | "hasVoted"
      | "refund"
      | "rejectCampaign"
      | "release"
      | "requests"
      | "submitProof"
      | "verifyCampaign"
      | "vote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approved"
      | "CampaignCreated"
      | "CampaignFailed"
      | "CampaignRejected"
      | "CampaignVerified"
      | "Donated"
      | "FundingClosed"
      | "ProofSubmitted"
      | "Refunded"
      | "Released"
      | "RequestApproved"
      | "RequestClosed"
      | "RequestCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveRequest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAndUpdateCampaignFailure",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkProofHash",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closeExpiredRequest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [BigNumberish, BigNumberish, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createRequest",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "donate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "donations",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasOverdueProof",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectCampaign",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "release",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requests",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkAndUpdateCampaignFailure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkProofHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeExpiredRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "donations", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRequest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasOverdueProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rejectCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace ApprovedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    requestId: BigNumberish,
    donor: AddressLike,
    weight: BigNumberish,
    currentApprovalWeight: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    requestId: bigint,
    donor: string,
    weight: bigint,
    currentApprovalWeight: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    requestId: bigint;
    donor: string;
    weight: bigint;
    currentApprovalWeight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    creator: AddressLike,
    verifier: AddressLike,
    goal: BigNumberish,
    deadline: BigNumberish,
    metadataHash: BytesLike
  ];
  export type OutputTuple = [
    campaignId: bigint,
    creator: string,
    verifier: string,
    goal: bigint,
    deadline: bigint,
    metadataHash: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    creator: string;
    verifier: string;
    goal: bigint;
    deadline: bigint;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignFailedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    totalDonated: BigNumberish,
    goal: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    totalDonated: bigint,
    goal: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    totalDonated: bigint;
    goal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignRejectedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    verifier: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    campaignId: bigint,
    verifier: string,
    reason: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    verifier: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignVerifiedEvent {
  export type InputTuple = [campaignId: BigNumberish, verifier: AddressLike];
  export type OutputTuple = [campaignId: bigint, verifier: string];
  export interface OutputObject {
    campaignId: bigint;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DonatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    donor: AddressLike,
    amount: BigNumberish,
    totalDonated: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    donor: string,
    amount: bigint,
    totalDonated: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    donor: string;
    amount: bigint;
    totalDonated: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundingClosedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    totalRaised: BigNumberish
  ];
  export type OutputTuple = [campaignId: bigint, totalRaised: bigint];
  export interface OutputObject {
    campaignId: bigint;
    totalRaised: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofSubmittedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    requestId: BigNumberish,
    receiptHash: BytesLike,
    isLate: boolean,
    submittedAt: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    requestId: bigint,
    receiptHash: string,
    isLate: boolean,
    submittedAt: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    requestId: bigint;
    receiptHash: string;
    isLate: boolean;
    submittedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    donor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [campaignId: bigint, donor: string, amount: bigint];
  export interface OutputObject {
    campaignId: bigint;
    donor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleasedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    requestId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    requestId: bigint,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    requestId: bigint;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestApprovedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    requestId: BigNumberish,
    totalApprovalWeight: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    requestId: bigint,
    totalApprovalWeight: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    requestId: bigint;
    totalApprovalWeight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestClosedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    requestId: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    campaignId: bigint,
    requestId: bigint,
    reason: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    requestId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestCreatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    requestId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish,
    requestHash: BytesLike,
    votingDeadline: BigNumberish,
    proofDeadline: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    requestId: bigint,
    recipient: string,
    amount: bigint,
    requestHash: string,
    votingDeadline: bigint,
    proofDeadline: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    requestId: bigint;
    recipient: string;
    amount: bigint;
    requestHash: string;
    votingDeadline: bigint;
    proofDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FundTrace extends BaseContract {
  connect(runner?: ContractRunner | null): FundTrace;
  waitForDeployment(): Promise<this>;

  interface: FundTraceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveRequest: TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  campaignCount: TypedContractMethod<[], [bigint], "view">;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        creator: string;
        verifier: string;
        goal: bigint;
        deadline: bigint;
        totalDonated: bigint;
        totalReleased: bigint;
        metadataHash: string;
        state: bigint;
        requestCount: bigint;
        activeRequestId: bigint;
      }
    ],
    "view"
  >;

  checkAndUpdateCampaignFailure: TypedContractMethod<
    [_campaignId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  checkProofHash: TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _requestId: BigNumberish,
      _candidateHash: BytesLike
    ],
    [
      [boolean, boolean, bigint] & {
        matches: boolean;
        isSubmitted: boolean;
        timing: bigint;
      }
    ],
    "view"
  >;

  closeExpiredRequest: TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createCampaign: TypedContractMethod<
    [
      _goal: BigNumberish,
      _deadline: BigNumberish,
      _metadataHash: BytesLike,
      _verifier: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  createRequest: TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _recipient: AddressLike,
      _amount: BigNumberish,
      _requestHash: BytesLike,
      _votingDuration: BigNumberish,
      _proofDuration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  donate: TypedContractMethod<[_campaignId: BigNumberish], [void], "payable">;

  donations: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getCampaign: TypedContractMethod<
    [_campaignId: BigNumberish],
    [FundTrace.CampaignStructOutput],
    "view"
  >;

  getRequest: TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [FundTrace.RequestStructOutput],
    "view"
  >;

  hasOverdueProof: TypedContractMethod<
    [_campaignId: BigNumberish],
    [boolean],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [boolean],
    "view"
  >;

  refund: TypedContractMethod<
    [_campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  rejectCampaign: TypedContractMethod<
    [_campaignId: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;

  release: TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  requests: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        recipient: string;
        amount: bigint;
        requestHash: string;
        votingDeadline: bigint;
        proofDeadline: bigint;
        approvalWeight: bigint;
        state: bigint;
        receiptHash: string;
        proofSubmitted: boolean;
        releasedAt: bigint;
        proofSubmittedAt: bigint;
        timing: bigint;
      }
    ],
    "view"
  >;

  submitProof: TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _requestId: BigNumberish,
      _receiptHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  verifyCampaign: TypedContractMethod<
    [_campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveRequest"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "campaignCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        creator: string;
        verifier: string;
        goal: bigint;
        deadline: bigint;
        totalDonated: bigint;
        totalReleased: bigint;
        metadataHash: string;
        state: bigint;
        requestCount: bigint;
        activeRequestId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkAndUpdateCampaignFailure"
  ): TypedContractMethod<[_campaignId: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "checkProofHash"
  ): TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _requestId: BigNumberish,
      _candidateHash: BytesLike
    ],
    [
      [boolean, boolean, bigint] & {
        matches: boolean;
        isSubmitted: boolean;
        timing: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "closeExpiredRequest"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      _goal: BigNumberish,
      _deadline: BigNumberish,
      _metadataHash: BytesLike,
      _verifier: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createRequest"
  ): TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _recipient: AddressLike,
      _amount: BigNumberish,
      _requestHash: BytesLike,
      _votingDuration: BigNumberish,
      _proofDuration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "donate"
  ): TypedContractMethod<[_campaignId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "donations"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCampaign"
  ): TypedContractMethod<
    [_campaignId: BigNumberish],
    [FundTrace.CampaignStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRequest"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [FundTrace.RequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasOverdueProof"
  ): TypedContractMethod<[_campaignId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[_campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rejectCampaign"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        recipient: string;
        amount: bigint;
        requestHash: string;
        votingDeadline: bigint;
        proofDeadline: bigint;
        approvalWeight: bigint;
        state: bigint;
        receiptHash: string;
        proofSubmitted: boolean;
        releasedAt: bigint;
        proofSubmittedAt: bigint;
        timing: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _requestId: BigNumberish,
      _receiptHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyCampaign"
  ): TypedContractMethod<[_campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Approved"
  ): TypedContractEvent<
    ApprovedEvent.InputTuple,
    ApprovedEvent.OutputTuple,
    ApprovedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignFailed"
  ): TypedContractEvent<
    CampaignFailedEvent.InputTuple,
    CampaignFailedEvent.OutputTuple,
    CampaignFailedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignRejected"
  ): TypedContractEvent<
    CampaignRejectedEvent.InputTuple,
    CampaignRejectedEvent.OutputTuple,
    CampaignRejectedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignVerified"
  ): TypedContractEvent<
    CampaignVerifiedEvent.InputTuple,
    CampaignVerifiedEvent.OutputTuple,
    CampaignVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "Donated"
  ): TypedContractEvent<
    DonatedEvent.InputTuple,
    DonatedEvent.OutputTuple,
    DonatedEvent.OutputObject
  >;
  getEvent(
    key: "FundingClosed"
  ): TypedContractEvent<
    FundingClosedEvent.InputTuple,
    FundingClosedEvent.OutputTuple,
    FundingClosedEvent.OutputObject
  >;
  getEvent(
    key: "ProofSubmitted"
  ): TypedContractEvent<
    ProofSubmittedEvent.InputTuple,
    ProofSubmittedEvent.OutputTuple,
    ProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "Refunded"
  ): TypedContractEvent<
    RefundedEvent.InputTuple,
    RefundedEvent.OutputTuple,
    RefundedEvent.OutputObject
  >;
  getEvent(
    key: "Released"
  ): TypedContractEvent<
    ReleasedEvent.InputTuple,
    ReleasedEvent.OutputTuple,
    ReleasedEvent.OutputObject
  >;
  getEvent(
    key: "RequestApproved"
  ): TypedContractEvent<
    RequestApprovedEvent.InputTuple,
    RequestApprovedEvent.OutputTuple,
    RequestApprovedEvent.OutputObject
  >;
  getEvent(
    key: "RequestClosed"
  ): TypedContractEvent<
    RequestClosedEvent.InputTuple,
    RequestClosedEvent.OutputTuple,
    RequestClosedEvent.OutputObject
  >;
  getEvent(
    key: "RequestCreated"
  ): TypedContractEvent<
    RequestCreatedEvent.InputTuple,
    RequestCreatedEvent.OutputTuple,
    RequestCreatedEvent.OutputObject
  >;

  filters: {
    "Approved(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      ApprovedEvent.InputTuple,
      ApprovedEvent.OutputTuple,
      ApprovedEvent.OutputObject
    >;
    Approved: TypedContractEvent<
      ApprovedEvent.InputTuple,
      ApprovedEvent.OutputTuple,
      ApprovedEvent.OutputObject
    >;

    "CampaignCreated(uint256,address,address,uint256,uint256,bytes32)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "CampaignFailed(uint256,uint256,uint256)": TypedContractEvent<
      CampaignFailedEvent.InputTuple,
      CampaignFailedEvent.OutputTuple,
      CampaignFailedEvent.OutputObject
    >;
    CampaignFailed: TypedContractEvent<
      CampaignFailedEvent.InputTuple,
      CampaignFailedEvent.OutputTuple,
      CampaignFailedEvent.OutputObject
    >;

    "CampaignRejected(uint256,address,string)": TypedContractEvent<
      CampaignRejectedEvent.InputTuple,
      CampaignRejectedEvent.OutputTuple,
      CampaignRejectedEvent.OutputObject
    >;
    CampaignRejected: TypedContractEvent<
      CampaignRejectedEvent.InputTuple,
      CampaignRejectedEvent.OutputTuple,
      CampaignRejectedEvent.OutputObject
    >;

    "CampaignVerified(uint256,address)": TypedContractEvent<
      CampaignVerifiedEvent.InputTuple,
      CampaignVerifiedEvent.OutputTuple,
      CampaignVerifiedEvent.OutputObject
    >;
    CampaignVerified: TypedContractEvent<
      CampaignVerifiedEvent.InputTuple,
      CampaignVerifiedEvent.OutputTuple,
      CampaignVerifiedEvent.OutputObject
    >;

    "Donated(uint256,address,uint256,uint256)": TypedContractEvent<
      DonatedEvent.InputTuple,
      DonatedEvent.OutputTuple,
      DonatedEvent.OutputObject
    >;
    Donated: TypedContractEvent<
      DonatedEvent.InputTuple,
      DonatedEvent.OutputTuple,
      DonatedEvent.OutputObject
    >;

    "FundingClosed(uint256,uint256)": TypedContractEvent<
      FundingClosedEvent.InputTuple,
      FundingClosedEvent.OutputTuple,
      FundingClosedEvent.OutputObject
    >;
    FundingClosed: TypedContractEvent<
      FundingClosedEvent.InputTuple,
      FundingClosedEvent.OutputTuple,
      FundingClosedEvent.OutputObject
    >;

    "ProofSubmitted(uint256,uint256,bytes32,bool,uint256)": TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;
    ProofSubmitted: TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;

    "Refunded(uint256,address,uint256)": TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
    Refunded: TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;

    "Released(uint256,uint256,address,uint256)": TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;
    Released: TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;

    "RequestApproved(uint256,uint256,uint256)": TypedContractEvent<
      RequestApprovedEvent.InputTuple,
      RequestApprovedEvent.OutputTuple,
      RequestApprovedEvent.OutputObject
    >;
    RequestApproved: TypedContractEvent<
      RequestApprovedEvent.InputTuple,
      RequestApprovedEvent.OutputTuple,
      RequestApprovedEvent.OutputObject
    >;

    "RequestClosed(uint256,uint256,string)": TypedContractEvent<
      RequestClosedEvent.InputTuple,
      RequestClosedEvent.OutputTuple,
      RequestClosedEvent.OutputObject
    >;
    RequestClosed: TypedContractEvent<
      RequestClosedEvent.InputTuple,
      RequestClosedEvent.OutputTuple,
      RequestClosedEvent.OutputObject
    >;

    "RequestCreated(uint256,uint256,address,uint256,bytes32,uint256,uint256)": TypedContractEvent<
      RequestCreatedEvent.InputTuple,
      RequestCreatedEvent.OutputTuple,
      RequestCreatedEvent.OutputObject
    >;
    RequestCreated: TypedContractEvent<
      RequestCreatedEvent.InputTuple,
      RequestCreatedEvent.OutputTuple,
      RequestCreatedEvent.OutputObject
    >;
  };
}
